name: Specs

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC

jobs:
  specs:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.crystal == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        crystal: [
          '1.17.1',
          '1.18.2',
          '1.19.1',
          'nightly',
        ]
    container:
      image: crystallang/crystal:${{ matrix.crystal }}
    steps:
      - name: "[Git] Checkout code"
        uses: actions/checkout@v4.2.2

      - name: Install required packages
        run: |
          apt-get update
          apt-get -yqq install libsqlite3-dev curl

      - name: Cache Crystal
        uses: actions/cache@v4.2.3
        with:
          path: ~/.cache/crystal
          key: ${{ runner.os }}-crystal-${{ matrix.crystal }}-${{ hashFiles('shard.lock') }}
          restore-keys: |
            ${{ runner.os }}-crystal-${{ matrix.crystal }}-

      - name: Cache shards
        uses: actions/cache@v4.2.3
        with:
          path: lib
          key: ${{ runner.os }}-shards-${{ hashFiles('shard.lock') }}

      - name: Install shards
        run: shards install --ignore-crystal-version

      - name: Run specs
        run: crystal spec -v --error-trace --no-color
